Library/Controllers/LibraryController.cs
using Library.Service;
using Microsoft.AspNetCore.Mvc;
using Library.ViewModel;
using Library.Models;
using Microsoft.EntityFrameworkCore;
using Library.Data;

namespace Library.Controllers
{
	public class LibraryController : Controller
	{
		private readonly IlibraryService _libraryService;
		private readonly ApplicationDBContext _Context;


		public LibraryController(ApplicationDBContext dbContext, IlibraryService libraryService)
		{
			_Context = dbContext;
			_libraryService = libraryService;
		}


		public async Task<IActionResult> Index() =>
			View(await _libraryService.GetAllLibraries());


		public IActionResult Create()
		{
			return View();
		}


		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(LibraryVM libraryVM)
		{

			if (!ModelState.IsValid)
			{
				return View("ErorLibrary");
			}

			if (await _libraryService.IsLibraryExists(libraryVM))
			{
				return View("LibraryExists");
			}

			bool success = await _libraryService.CreateNewLibrary(libraryVM);
			if (success) return RedirectToAction("Index");
			return View("ErorLibrary");

		}
	}
}

Library/Controllers/ShelfController.cs
using Library.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Library.Models;
using Library.ViewModel;
using Library.Service;
using Library.ViewModels;

namespace Library.Controllers
{
	public class ShelfController : Controller
	{
		private readonly ApplicationDBContext _Context;
		private readonly IShelfService _ishelfService;



		public ShelfController(ApplicationDBContext context, IShelfService shelfService)
		{
			_Context = context;
			_ishelfService = shelfService;
		}


		public async Task<IActionResult> Index(long id)
		{

			ViewBag.LibraryId = id;
			return View(await _ishelfService.GetAllShelves(id));
		}


		public IActionResult Create(long libraryId)
		{
			ViewBag.LibraryId = libraryId;
			return View();
		}


		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(ShelfVM shelfVM)
		{
			try
			{
				await _ishelfService.CreateNewShelf(shelfVM);
			}
			catch (Exception ex)
			{
                ModelState.AddModelError("createError", ex.Message);
                return View();
            }

            return RedirectToAction("Index", new { id = shelfVM.LibraryId });
		}
	}
}

Library/Views/Library/Create.cshtml
@model Library.ViewModel.LibraryVM

@Html.AntiForgeryToken();

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>LibraryVM</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                @if (!ViewData.ModelState.IsValid)
                {
                    <div class="alert alert-danger">
                        <ul>
                            @foreach (var modelState in ViewData.ModelState.Values)
                            {
                                @foreach (var error in modelState.Errors)
                                {
                                    <li>@error.ErrorMessage</li>
                                }
                            }
                        </ul>
                    </div>
                }
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Library/Views/Library/ErorLibrary.cshtml
<h1>The library is invalid, try again!</h1>

Library/Views/Library/Index.cshtml
@model IEnumerable<Library.Models.LibraryModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Libraries</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th hidden>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genre)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td hidden>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genre)
            </td>
            <td>
                @Html.ActionLink("Shelves", "Index","Shelf", new { id = item.Id}) |
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ }) 
            </td>
        </tr>
}
    </tbody>
</table>

Library/Views/Library/LibraryExists.cshtml
<h1>The library is already exists</h1>