Library/Controllers/LibraryController.cs
using Library.Service;
using Microsoft.AspNetCore.Mvc;
using Library.ViewModel;
using Library.Models;
using Microsoft.EntityFrameworkCore;
using Library.Data;

namespace Library.Controllers
{
	public class LibraryController : Controller
	{
		private readonly IlibraryService _libraryService;
		private readonly ApplicationDBContext _Context;


		public LibraryController(ApplicationDBContext dbContext, IlibraryService libraryService)
		{
			_Context = dbContext;
			_libraryService = libraryService;
		}


		public async Task<IActionResult> Index() =>
			View(await _libraryService.GetAllLibraries());


		public IActionResult Create()
		{
			return View();
		}


		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(LibraryVM libraryVM)
		{

			if (!ModelState.IsValid)
			{
				return View("ErorLibrary");
			}

			if (await _libraryService.IsLibraryExists(libraryVM))
			{
				return View("LibraryExists");
			}

			bool success = await _libraryService.CreateNewLibrary(libraryVM);
			if (success) return RedirectToAction("Index");
			return View("ErorLibrary");

		}
	}
}

Library/Controllers/SetController.cs
using Humanizer.Localisation;
using Library.Service;
using Library.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Library.Controllers
{
    public class SetController : Controller
    {
        private readonly ISetService _setService;

        public SetController(ISetService setService)
        {
            _setService = setService;
        }

        public async Task<IActionResult> Index(long shelfId)
        {
            ViewBag.ShelfId = shelfId;
            return View( await _setService.GetAllSetsByShelfId(shelfId));
        }

        public IActionResult Create(long shelfId)
        {
            ViewBag.ShelfId = shelfId;
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SetVM setVM) 
        {
            try
            {
                await _setService.CreateNewSet(setVM);
                return RedirectToAction("Index", new { shelfId = setVM.ShelfId });
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("createError", ex.Message);
                return View();
            }

        }




    }
}

Library/Controllers/ShelfController.cs
using Library.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Library.Models;
using Library.ViewModel;
using Library.Service;
using Library.ViewModels;

namespace Library.Controllers
{
	public class ShelfController : Controller
	{
		private readonly ApplicationDBContext _Context;
		private readonly IShelfService _ishelfService;



		public ShelfController(ApplicationDBContext context, IShelfService shelfService)
		{
			_Context = context;
			_ishelfService = shelfService;
		}


		public async Task<IActionResult> Index(long id)
		{

			ViewBag.LibraryId = id;
			return View(await _ishelfService.GetAllShelves(id));
		}


		public IActionResult Create(long libraryId)
		{
			ViewBag.LibraryId = libraryId;
			return View();
		}


		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(ShelfVM shelfVM)
		{
			try
			{
				await _ishelfService.CreateNewShelf(shelfVM);
			}
			catch (Exception ex)
			{
                ModelState.AddModelError("createError", ex.Message);
                return View();
            }

            return RedirectToAction("Index", new { id = shelfVM.LibraryId });
		}
	}
}

Library/Views/Shelf/Create.cshtml
@model Library.ViewModels.ShelfVM

@Html.AntiForgeryToken();

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ShelfVM</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Width" class="control-label"></label>
                <input asp-for="Width" class="form-control" />
                <span asp-validation-for="Width" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Height" class="control-label"></label>
                <input asp-for="Height" class="form-control" />
                <span asp-validation-for="Height" class="text-danger"></span>
            </div>
                <input asp-for="LibraryId" value="@ViewBag.LibraryId" class="form-control" hidden />
            
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                @if (!ViewData.ModelState.IsValid)
                {
                    <div class="alert alert-danger">
                        <ul>
                            @foreach (var modelState in ViewData.ModelState.Values)
                            {
                                @foreach (var error in modelState.Errors)
                                {
                                    <li>@error.ErrorMessage</li>
                                }
                            }
                        </ul>
                    </div>
                }
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Library/Views/Shelf/Index.cshtml
@model IEnumerable<Library.Models.ShelfModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Shelves</h1>

<p>
    @Html.ActionLink("Create New", "Create", new { libraryId = ViewBag.LibraryId })
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Width)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Height)
            </th>
            <th hidden>
                @Html.DisplayNameFor(model => model.LibraryId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Width)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Height)
            </td>
            <td hidden>
                @Html.DisplayFor(modelItem => item.LibraryId)
            </td>
            <td>
                @Html.ActionLink("Sets", "Index","Set", new { shelfid = item.Id }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>
<div>
    @Html.ActionLink("Back to Library", "Index", "Library", new { /* id=item.PrimaryKey */ })
</div>